infrastructure:
  project_id: iamabhi45
  zone: europe-west4-a
  network: default
data_parquet_path: gs://buckets45/data/processed/default_run/train.parquet
text_column_name: cleaned_text
tokenizer:
  _target_: abhishek.tokenization.tokenizers.HuggingFaceTokenizer
  pre_tokenizer:
    _target_: tokenizers.pre_tokenizers.Whitespace
  model:
    _target_: tokenizers.models.BPE
    vocab: null
    merges: null
    cache_capacity: 10000
    dropout: null
    unk_token: '[UNK]'
    fuse_unk: false
  trainer:
    _target_: tokenizers.trainers.BpeTrainer
    vocab_size: 30000
    show_progress: true
    min_frequency: 0
    special_tokens:
    - '[UNK]'
    - '[CLS]'
    - '[SEP]'
    - '[PAD]'
    - '[MASK]'
    initial_alphabet: []
  normalizer: null
  decoder: null
  post_processor: null
  unk_token: '[UNK]'
  cls_token: '[CLS]'
  sep_token: '[SEP]'
  pad_token: '[PAD]'
  mask_token: '[MASK]'
docker_image_name: europe-west4-docker.pkg.dev/iamabhi45/abhishek/abhishek-data-processing
docker_image_tag: 055f8b4c-0862-4177-b961-ef4b5a7731d9
